networks:
  todolist:

volumes:
  postgres:

services:
  postgres:
    image: postgres:alpine
    networks:
      - todolist
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=confia
      - POSTGRES_PASSWORD=confia

  todolist:
    build: .
    ports:
      - "5000:5000/tcp"
    networks:
      - todolist
    depends_on:
      - postgres
    environment:
      - DB_URI=postgresql://confia:confia@postgres/
